language: php

php:
- 7.2

before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'

script:
- vendor/bin/phpunit

services:
- mysql

addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server

dist: trusty

sudo: required

cache:
  directories:
  - vendor