openapi: "3.0.0"
info:
  version: 1.0.0
  title: API for Picker Tweaker
paths:
  /register:
    post:
      summary: Register user
      operationId: userRegister
      tags:
      - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Return current user model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /login:
    post:
      summary: Authenticate
      operationId: userLogin
      tags:
      - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Return current user model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /user:
    get:
      summary: Get current user
      operationId: currentUser
      tags:
      - user
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Return current user model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /categories:
    get:
      summary: Get categories
      operationId: categoryList
      tags:
      - category
      security:
      - bearerAuth: []
      parameters:
      - name: name
        in: query
        description: Part of name
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Return category list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
components:
  schemas:
    User:
      required:
      - name
      - email
      - password
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
    Category:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT